name: Test HDF5 GPUDirect Storage VFD
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout vfd-gds
      uses: actions/checkout@v2
    - name: Checkout HDF5
      uses: actions/checkout@v2
      with:
        repository: HDFGroup/hdf5
        path: hdf5
    - name: Install dependencies
      run: sudo apt-get install ninja-build automake autoconf libtool libtool-bin libopenmpi-dev libpthread-stubs0-dev

    # - name: Install CUDA        
    #  uses: Jimver/cuda-toolkit@v0.2.4
    #  with:
    #    cuda: '11.2.2'
    - name: Install GDS/CUDA
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
        sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
        sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
        sudo apt-get update
        sudo apt-get -y install cuda
    - name: Install HDF5
      run: |
        cmake --version
        mkdir hdf5/build
        cd hdf5/build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DHDF5_ENABLE_PARALLEL:BOOL=ON -DHDF5_ENABLE_THREADSAFE:BOOL=ON -DALLOW_UNSUPPORTED:BOOL=ON ..
        sudo make -j2 install
        cd ..
        git rev-parse HEAD > git.txt
      
    - name: Install vfd-gds
      env:
        HDF5_PLUGIN_PATH: /usr/local/lib
        LD_LIBRARY_PATH: /usr/local/lib:$LD_LIBRARY_PATH
        CUDACXX: /usr/local/cuda/bin/nvcc
      run: |
        set
        ls -lrv /usr/local/
        mkdir build
        cd build
        cmake .. -DHDF5_DIR=/usr/local
        sudo make -j2 install
        ls /usr/local/lib
        ctest --output-on-failure
